version: '2'
plugins:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: __ESLINT_CHANNEL__
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-92
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - '**/node_modules/'
  - script/
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - Tests/
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
  - '**/*.min.js'
  - '**/*.min.css'
  - '**/__tests__/'
  - '**/__mocks__/'
  - '**/Acticlass-App/'
  - Acticlass-App/
