stages: # List of stages for jobs, and their order of execution
  - build
  - test
#   - deploy

variables:
  NODE_IMAGE: 'node:16.15.1'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - Acticlass-App/node_modules/
    - Acticlass-API/node_modules/

build_fronted:
  stage: build
  image: $NODE_IMAGE
  script:
    - cd Acticlass-App
    - npm install

build_backend:
  stage: build
  image: $NODE_IMAGE
  script:
    - cd Acticlass-API
    - npm install

test_frontend:
  stage: test
  image: $NODE_IMAGE
  script:
    - cd Acticlass-App    
    - npm test

test_backend:
  stage: test
  image: $NODE_IMAGE
  script:
    - cd Acticlass-API    
    - npm test
