stages:
  # - build
  # - test
  - deploy

variables:
  NODE_IMAGE: "node:16.15.1"
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - Acticlass-App/node_modules/
#     - Acticlass-API/node_modules/

# build_fronted:
#   stage: build
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-App
#     - npm install

# build_backend:
#   stage: build
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-API
#     - npm install

# test_frontend:
#   stage: test
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-App
#     - npm install
#     - npm test

# test_backend:
#   stage: test
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-API
#     - npm install
#     - npm test

publish:
  stage: deploy
  tags:
    - acticlass-runner
  script:
    - ls
    - cp ./config.json $CI_PROJECT_DIR/config.json  # Copy the Docker config into the project directory
    - docker login -u $DOCKERHUB_USERNAME --password-stdin < config.json
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
