stages:
  - build
  - test
  - deploy

variables:
  NODE_IMAGE: "node:16.15.1"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - Acticlass-App/node_modules/
    - Acticlass-API/node_modules/

build_fronted:
  stage: build
  image: $NODE_IMAGE
  tags:
    - acticlass-runner
  script:
    - cd Acticlass-App
    - npm install

build_backend:
  stage: build
  image: $NODE_IMAGE
  tags:
    - acticlass-runner
  script:
    - cd Acticlass-API
    - npm install

test_frontend:
  stage: test
  image: $NODE_IMAGE
  tags:
    - acticlass-runner
  script:
    - cd Acticlass-App
    - npm install
    - npm test

test_backend:
  stage: test
  image: $NODE_IMAGE
  tags:
    - acticlass-runner
  script:
    - cd Acticlass-API
    - npm install
    - npm test

deploy:
  stage: deploy
  tags:
    - acticlass-runner
  script:
    - echo "$ID_RSA" | tr -d '\r' > ~/deployer/.ssh/id_rsa
    - chmod 600 ~/deployer/.ssh/id_rsa
    - ssh-keyscan <$SERVER_IP> >> ~/deployer/.ssh/known_hosts
    - scp -r * deployer@<$SERVER_IP>:~/deployer/app  # Copy your application files to the VM
    - ssh deployer@<$SERVER_IP> "cd ~/deployer/app && npm install && npm start"  # SSH into VM, install dependencies, and start the application  
  
