stages:
  # - build
  # - test
  - publish
  - deploy

variables:
  NODE_IMAGE: 'node:16.15.1'

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - Acticlass-App/node_modules/
#     - Acticlass-API/node_modules/

# build_fronted:
#   stage: build
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-App
#     - npm install

# build_backend:
#   stage: build
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-API
#     - npm install

# test_frontend:
#   stage: test
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-App
#     - npm install
#     - npm test

# test_backend:
#   stage: test
#   image: $NODE_IMAGE
#   tags:
#     - acticlass-runner
#   script:
#     - cd Acticlass-API
#     - npm install
#     - npm test

publish:
  image: docker:latest
  stage: publish
  tags:
    - acticlass-runner
  variables:
    # these values may need to be different if using TLS, k8s, etc.
    # You can alternatively set defaults in your runner config
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: 'tcp://docker:2375'
  services:
    - docker:dind
  script:
    - pwd
    - echo $SERVER_IP
    - docker --version
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD docker.io
    - docker build -t docker.io/acticlass/acticlass:$CI_COMMIT_SHORT_SHA .
    - docker push docker.io/acticlass/acticlass:$CI_COMMIT_SHORT_SHA
